<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datas = [
            [
                'data' => [
                    'id' => 1102015214,
                    'node_id' => 'R_kgDOQa9q7g',
                    'name' => 'shopedia-frontend',
                    'full_name' => 'dedyasxkaguya/shopedia-frontend',
                    'private' => false,
                    'owner' => [
                        'login' => 'dedyasxkaguya',
                        'id' => 226875674,
                        'node_id' => 'U_kgDODYXZGg',
                        'avatar_url' => 'https://avatars.githubusercontent.com/u/226875674?v=4',
                        'gravatar_id' => '',
                        'url' => 'https://api.github.com/users/dedyasxkaguya',
                        'html_url' => 'https://github.com/dedyasxkaguya',
                        'followers_url' => 'https://api.github.com/users/dedyasxkaguya/followers',
                        'following_url' => 'https://api.github.com/users/dedyasxkaguya/following{/other_user}',
                        'gists_url' => 'https://api.github.com/users/dedyasxkaguya/gists{/gist_id}',
                        'starred_url' => 'https://api.github.com/users/dedyasxkaguya/starred{/owner}{/repo}',
                        'subscriptions_url' => 'https://api.github.com/users/dedyasxkaguya/subscriptions',
                        'organizations_url' => 'https://api.github.com/users/dedyasxkaguya/orgs',
                        'repos_url' => 'https://api.github.com/users/dedyasxkaguya/repos',
                        'events_url' => 'https://api.github.com/users/dedyasxkaguya/events{/privacy}',
                        'received_events_url' => 'https://api.github.com/users/dedyasxkaguya/received_events',
                        'type' => 'User',
                        'user_view_type' => 'public',
                        'site_admin' => false,
                    ],
                    'html_url' => 'https://github.com/dedyasxkaguya/shopedia-frontend',
                    'description' => null,
                    'fork' => false,
                    'url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend',
                    'forks_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/forks',
                    'keys_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/keys{/key_id}',
                    'collaborators_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/collaborators{/collaborator}',
                    'teams_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/teams',
                    'hooks_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/hooks',
                    'issue_events_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/issues/events{/number}',
                    'events_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/events',
                    'assignees_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/assignees{/user}',
                    'branches_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/branches{/branch}',
                    'tags_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/tags',
                    'blobs_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/git/blobs{/sha}',
                    'git_tags_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/git/tags{/sha}',
                    'git_refs_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/git/refs{/sha}',
                    'trees_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/git/trees{/sha}',
                    'statuses_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/statuses/{sha}',
                    'languages_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/languages',
                    'stargazers_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/stargazers',
                    'contributors_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/contributors',
                    'subscribers_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/subscribers',
                    'subscription_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/subscription',
                    'commits_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/commits{/sha}',
                    'git_commits_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/git/commits{/sha}',
                    'comments_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/comments{/number}',
                    'issue_comment_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/issues/comments{/number}',
                    'contents_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/contents/{+path}',
                    'compare_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/compare/{base}...{head}',
                    'merges_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/merges',
                    'archive_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/{archive_format}{/ref}',
                    'downloads_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/downloads',
                    'issues_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/issues{/number}',
                    'pulls_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/pulls{/number}',
                    'milestones_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/milestones{/number}',
                    'notifications_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/notifications{?since,all,participating}',
                    'labels_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/labels{/name}',
                    'releases_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/releases{/id}',
                    'deployments_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia-frontend/deployments',
                    'created_at' => '2025-11-22T16:58:54Z',
                    'updated_at' => '2025-12-03T04:49:49Z',
                    'pushed_at' => '2025-12-03T04:49:46Z',
                    'git_url' => 'git://github.com/dedyasxkaguya/shopedia-frontend.git',
                    'ssh_url' => 'git@github.com:dedyasxkaguya/shopedia-frontend.git',
                    'clone_url' => 'https://github.com/dedyasxkaguya/shopedia-frontend.git',
                    'svn_url' => 'https://github.com/dedyasxkaguya/shopedia-frontend',
                    'homepage' => null,
                    'size' => 142,
                    'stargazers_count' => 0,
                    'watchers_count' => 0,
                    'language' => 'TypeScript',
                    'has_issues' => true,
                    'has_projects' => true,
                    'has_downloads' => true,
                    'has_wiki' => true,
                    'has_pages' => false,
                    'has_discussions' => false,
                    'forks_count' => 1,
                    'mirror_url' => null,
                    'archived' => false,
                    'disabled' => false,
                    'open_issues_count' => 0,
                    'license' => null,
                    'allow_forking' => true,
                    'is_template' => false,
                    'web_commit_signoff_required' => false,
                    'topics' => [],
                    'visibility' => 'public',
                    'forks' => 1,
                    'open_issues' => 0,
                    'watchers' => 0,
                    'default_branch' => 'master',
                    'temp_clone_token' => null,
                    'network_count' => 1,
                    'subscribers_count' => 0,
                ],
            ],
            [
                'data' => [
                    'id' => 1102006422,
                    'node_id' => 'R_kgDOQa9Ilg',
                    'name' => 'shopedia',
                    'full_name' => 'dedyasxkaguya/shopedia',
                    'private' => false,
                    'owner' => [
                        'login' => 'dedyasxkaguya',
                        'id' => 226875674,
                        'node_id' => 'U_kgDODYXZGg',
                        'avatar_url' => 'https://avatars.githubusercontent.com/u/226875674?v=4',
                        'gravatar_id' => '',
                        'url' => 'https://api.github.com/users/dedyasxkaguya',
                        'html_url' => 'https://github.com/dedyasxkaguya',
                        'followers_url' => 'https://api.github.com/users/dedyasxkaguya/followers',
                        'following_url' => 'https://api.github.com/users/dedyasxkaguya/following{/other_user}',
                        'gists_url' => 'https://api.github.com/users/dedyasxkaguya/gists{/gist_id}',
                        'starred_url' => 'https://api.github.com/users/dedyasxkaguya/starred{/owner}{/repo}',
                        'subscriptions_url' => 'https://api.github.com/users/dedyasxkaguya/subscriptions',
                        'organizations_url' => 'https://api.github.com/users/dedyasxkaguya/orgs',
                        'repos_url' => 'https://api.github.com/users/dedyasxkaguya/repos',
                        'events_url' => 'https://api.github.com/users/dedyasxkaguya/events{/privacy}',
                        'received_events_url' => 'https://api.github.com/users/dedyasxkaguya/received_events',
                        'type' => 'User',
                        'user_view_type' => 'public',
                        'site_admin' => false,
                    ],
                    'html_url' => 'https://github.com/dedyasxkaguya/shopedia',
                    'description' => null,
                    'fork' => false,
                    'url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia',
                    'forks_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/forks',
                    'keys_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/keys{/key_id}',
                    'collaborators_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/collaborators{/collaborator}',
                    'teams_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/teams',
                    'hooks_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/hooks',
                    'issue_events_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/issues/events{/number}',
                    'events_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/events',
                    'assignees_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/assignees{/user}',
                    'branches_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/branches{/branch}',
                    'tags_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/tags',
                    'blobs_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/git/blobs{/sha}',
                    'git_tags_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/git/tags{/sha}',
                    'git_refs_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/git/refs{/sha}',
                    'trees_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/git/trees{/sha}',
                    'statuses_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/statuses/{sha}',
                    'languages_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/languages',
                    'stargazers_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/stargazers',
                    'contributors_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/contributors',
                    'subscribers_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/subscribers',
                    'subscription_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/subscription',
                    'commits_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/commits{/sha}',
                    'git_commits_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/git/commits{/sha}',
                    'comments_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/comments{/number}',
                    'issue_comment_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/issues/comments{/number}',
                    'contents_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/contents/{+path}',
                    'compare_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/compare/{base}...{head}',
                    'merges_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/merges',
                    'archive_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/{archive_format}{/ref}',
                    'downloads_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/downloads',
                    'issues_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/issues{/number}',
                    'pulls_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/pulls{/number}',
                    'milestones_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/milestones{/number}',
                    'notifications_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/notifications{?since,all,participating}',
                    'labels_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/labels{/name}',
                    'releases_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/releases{/id}',
                    'deployments_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/deployments',
                    'created_at' => '2025-11-22T16:40:07Z',
                    'updated_at' => '2025-12-03T04:50:09Z',
                    'pushed_at' => '2025-12-03T04:50:06Z',
                    'git_url' => 'git://github.com/dedyasxkaguya/shopedia.git',
                    'ssh_url' => 'git@github.com:dedyasxkaguya/shopedia.git',
                    'clone_url' => 'https://github.com/dedyasxkaguya/shopedia.git',
                    'svn_url' => 'https://github.com/dedyasxkaguya/shopedia',
                    'homepage' => null,
                    'size' => 4617,
                    'stargazers_count' => 0,
                    'watchers_count' => 0,
                    'language' => 'PHP',
                    'has_issues' => true,
                    'has_projects' => true,
                    'has_downloads' => true,
                    'has_wiki' => true,
                    'has_pages' => false,
                    'has_discussions' => false,
                    'forks_count' => 0,
                    'mirror_url' => null,
                    'archived' => false,
                    'disabled' => false,
                    'open_issues_count' => 0,
                    'license' => null,
                    'allow_forking' => true,
                    'is_template' => false,
                    'web_commit_signoff_required' => false,
                    'topics' => [],
                    'visibility' => 'public',
                    'forks' => 0,
                    'open_issues' => 0,
                    'watchers' => 0,
                    'default_branch' => 'master',
                    'temp_clone_token' => null,
                    'network_count' => 0,
                    'subscribers_count' => 0,
                ],
            ],
            [
                'data' => [
                    'id' => 1102006422,
                    'node_id' => 'R_kgDOQa9Ilg',
                    'name' => 'shopedia',
                    'full_name' => 'dedyasxkaguya/shopedia',
                    'private' => false,
                    'owner' => [
                        'login' => 'dedyasxkaguya',
                        'id' => 226875674,
                        'node_id' => 'U_kgDODYXZGg',
                        'avatar_url' => 'https://avatars.githubusercontent.com/u/226875674?v=4',
                        'gravatar_id' => '',
                        'url' => 'https://api.github.com/users/dedyasxkaguya',
                        'html_url' => 'https://github.com/dedyasxkaguya',
                        'followers_url' => 'https://api.github.com/users/dedyasxkaguya/followers',
                        'following_url' => 'https://api.github.com/users/dedyasxkaguya/following{/other_user}',
                        'gists_url' => 'https://api.github.com/users/dedyasxkaguya/gists{/gist_id}',
                        'starred_url' => 'https://api.github.com/users/dedyasxkaguya/starred{/owner}{/repo}',
                        'subscriptions_url' => 'https://api.github.com/users/dedyasxkaguya/subscriptions',
                        'organizations_url' => 'https://api.github.com/users/dedyasxkaguya/orgs',
                        'repos_url' => 'https://api.github.com/users/dedyasxkaguya/repos',
                        'events_url' => 'https://api.github.com/users/dedyasxkaguya/events{/privacy}',
                        'received_events_url' => 'https://api.github.com/users/dedyasxkaguya/received_events',
                        'type' => 'User',
                        'user_view_type' => 'public',
                        'site_admin' => false,
                    ],
                    'html_url' => 'https://github.com/dedyasxkaguya/shopedia',
                    'description' => null,
                    'fork' => false,
                    'url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia',
                    'forks_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/forks',
                    'keys_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/keys{/key_id}',
                    'collaborators_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/collaborators{/collaborator}',
                    'teams_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/teams',
                    'hooks_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/hooks',
                    'issue_events_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/issues/events{/number}',
                    'events_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/events',
                    'assignees_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/assignees{/user}',
                    'branches_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/branches{/branch}',
                    'tags_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/tags',
                    'blobs_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/git/blobs{/sha}',
                    'git_tags_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/git/tags{/sha}',
                    'git_refs_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/git/refs{/sha}',
                    'trees_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/git/trees{/sha}',
                    'statuses_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/statuses/{sha}',
                    'languages_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/languages',
                    'stargazers_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/stargazers',
                    'contributors_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/contributors',
                    'subscribers_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/subscribers',
                    'subscription_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/subscription',
                    'commits_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/commits{/sha}',
                    'git_commits_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/git/commits{/sha}',
                    'comments_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/comments{/number}',
                    'issue_comment_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/issues/comments{/number}',
                    'contents_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/contents/{+path}',
                    'compare_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/compare/{base}...{head}',
                    'merges_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/merges',
                    'archive_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/{archive_format}{/ref}',
                    'downloads_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/downloads',
                    'issues_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/issues{/number}',
                    'pulls_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/pulls{/number}',
                    'milestones_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/milestones{/number}',
                    'notifications_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/notifications{?since,all,participating}',
                    'labels_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/labels{/name}',
                    'releases_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/releases{/id}',
                    'deployments_url' => 'https://api.github.com/repos/dedyasxkaguya/shopedia/deployments',
                    'created_at' => '2025-11-22T16:40:07Z',
                    'updated_at' => '2025-12-03T04:50:09Z',
                    'pushed_at' => '2025-12-03T04:50:06Z',
                    'git_url' => 'git://github.com/dedyasxkaguya/shopedia.git',
                    'ssh_url' => 'git@github.com:dedyasxkaguya/shopedia.git',
                    'clone_url' => 'https://github.com/dedyasxkaguya/shopedia.git',
                    'svn_url' => 'https://github.com/dedyasxkaguya/shopedia',
                    'homepage' => null,
                    'size' => 4617,
                    'stargazers_count' => 0,
                    'watchers_count' => 0,
                    'language' => 'PHP',
                    'has_issues' => true,
                    'has_projects' => true,
                    'has_downloads' => true,
                    'has_wiki' => true,
                    'has_pages' => false,
                    'has_discussions' => false,
                    'forks_count' => 0,
                    'mirror_url' => null,
                    'archived' => false,
                    'disabled' => false,
                    'open_issues_count' => 0,
                    'license' => null,
                    'allow_forking' => true,
                    'is_template' => false,
                    'web_commit_signoff_required' => false,
                    'topics' => [],
                    'visibility' => 'public',
                    'forks' => 0,
                    'open_issues' => 0,
                    'watchers' => 0,
                    'default_branch' => 'master',
                    'temp_clone_token' => null,
                    'network_count' => 0,
                    'subscribers_count' => 0,
                ],
            ],
        ];
        foreach($datas as $data){
            $user_id = fake()->randomElement([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]);
            DB::table('projects')->insert([
                'user'=>json_encode(User::find($user_id)),
                'data'=>json_encode($data['data']),
                'user_id'=>$user_id
            ]);
        }
    }
}
