<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Pest\Support\Str;

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
            $siswas = [
                [
                    'nis' => '202523180',
                    'nisn' => '0096402000',
                    'nama' => 'ADHELIA KHARUNISSA TOPARI',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 10',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-11-22',
                    'alamat' => 'Jl. Sedang Baru XII RT.016/05 Kel. Serdang Kec. Kemayoran 10650',
                ],
                [
                    'nis' => '202523181',
                    'nisn' => '0096725027',
                    'nama' => 'ADILAH HAMMAM AKRAM',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 3',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-08-04',
                    'alamat' => 'Jl. Balimatraman RT.008/06 Kel. Manggarai Kec. Tebet 12850',
                ],
                [
                    'nis' => '202523182',
                    'nisn' => '010027375',
                    'nama' => 'ADINDA AFIFAH PUTRI',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 221',
                    'tempat_lahir' => 'Sasaki',
                    'tanggal_lahir' => '2010-01-13',
                    'alamat' => 'Agung Barat 34 Blok B-3512 RT.005/010 Kel. Sunter Agung Kec. Tanjung Priok 14350',
                ],
                [
                    'nis' => '202523183',
                    'nisn' => '010175035',
                    'nama' => 'ADZAN AHLL FIQRI',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 119',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2010-02-15',
                    'alamat' => 'Jl. Cempaka Baru Timur No.6 RT.013/06 Kel. Cempaka Baru Kec. Kemayoran 10640',
                ],
                [
                    'nis' => '202523184',
                    'nisn' => '0098097426',
                    'nama' => 'AIRA SASKIA SAHWA',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 159',
                    'tempat_lahir' => 'Pandeglang',
                    'tanggal_lahir' => '2009-07-14',
                    'alamat' => 'Gg. Trikora II No.10A RT.008/05 Kel. Duri Utara Kec. Tambora 11270',
                ],
                [
                    'nis' => '202523185',
                    'nisn' => '011735681',
                    'nama' => 'ALMIRA RAKHADHIYA ARYACITADI',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 45',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2011-03-22',
                    'alamat' => 'Komplek Kodam Jaya RT.002/05 Kel. Kalideres Kec. Kalideres 11840',
                ],
                [
                    'nis' => '202523186',
                    'nisn' => '0083731355',
                    'nama' => 'ANNISA MAHARANI',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 132',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-06-19',
                    'alamat' => 'Kp. Muk RT.003/04 Kel. Kedaung Kali Angke Kec. Cengkareng 11710',
                ],
                [
                    'nis' => '202523187',
                    'nisn' => '0094520752',
                    'nama' => 'ANNISAH AGUSTIN',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 79',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-08-06',
                    'alamat' => 'Kebon Kosong 25 RT.004/003 Kel. Kebon Kosong Kec. Kemayoran 10630',
                ],
                [
                    'nis' => '202523188',
                    'nisn' => '0091677079',
                    'nama' => 'ARIF RAFFY FADLURAHMAN',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 79',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-11-06',
                    'alamat' => 'Serdang Baru No.20 RT.004/005 Kel. Serdang Kec. Kemayoran 10650',
                ],
                [
                    'nis' => '202523189',
                    'nisn' => '0097725144',
                    'nama' => 'ARYO AJI SADEWO',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 23',
                    'tempat_lahir' => 'Cirebon',
                    'tanggal_lahir' => '2009-01-16',
                    'alamat' => 'Jl. Mangga Dua VIII RT.012/05 Kel. Ancol Kec. Pademangan 14430',
                ],
                [
                    'nis' => '202523190',
                    'nisn' => '0096454384',
                    'nama' => 'CAHAYA',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 130',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-12-13',
                    'alamat' => 'Jl. Kota Bambu Utara RT.004/06 Kel. Kota Bambu Utara Kec. Palmerah 11420',
                ],
                [
                    'nis' => '202523191',
                    'nisn' => '0096851334',
                    'nama' => 'CALLYLA SAKHI FAHRA',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 116',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-06-29',
                    'alamat' => 'Jl. Ancol Selatan No.4 RT.016/001 Kel. Sunter Agung Kec. Tanjung Priok 14350',
                ],
                [
                    'nis' => '202523192',
                    'nisn' => '0091839574',
                    'nama' => 'DEDY ANANG SETIAWAN',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 119',
                    'tempat_lahir' => 'Ponorogo',
                    'tanggal_lahir' => '2009-12-03',
                    'alamat' => 'Jl. Kp. Irian Gg. 30 No.14 RT.017/06 Kel. Serdang Kec. Kemayoran 10650',
                ],
                [
                    'nis' => '202523193',
                    'nisn' => '0092354639',
                    'nama' => 'DEJE ENNE DANI ROSALINE',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP AL KAMAL',
                    'tempat_lahir' => 'Penang',
                    'tanggal_lahir' => '2009-06-12',
                    'alamat' => 'Pesing Gaodo RT.009/06 Kel. Kedoya Utara Kec. Kebon Jeruk 11520',
                ],
                [
                    'nis' => '202523194',
                    'nisn' => '0093234009',
                    'nama' => 'DEWA NYOMAN ZED ZAMUEL ZOUSEUF',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 239',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-10-01',
                    'alamat' => 'Jl. Merak Mas Blok E5 No.27 RT.001/01 Kel. Tanjung Barat Kec. Jagakarsa 12530',
                ],
                [
                    'nis' => '202523195',
                    'nisn' => '0092431489',
                    'nama' => 'FERSYA WULANDA',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 69',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-04-01',
                    'alamat' => 'Jl. Semangka III/19 RT.010/07 Kel. Jati Pulo Kec. Palmerah 11430',
                ],
                [
                    'nis' => '202523196',
                    'nisn' => '0097885802',
                    'nama' => 'IHSAN HAFIDZ ASSIDIQ',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 40',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-05-13',
                    'alamat' => 'Jl. Karet Pasar Baru Barat II RT.016/015 Kel. Karet Tengsin Kec. Tanah Abang 10220',
                ],
                [
                    'nis' => '202523197',
                    'nisn' => '0091558244',
                    'nama' => 'INTAN NURHIKMAH',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 159',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-06-02',
                    'alamat' => 'Krendang Timur RT.004/001 Kel. Krendang Kec. Tambora 11260',
                ],
                [
                    'nis' => '202523198',
                    'nisn' => '0092279517',
                    'nama' => 'K\'SATRIA ALI',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 151',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2008-03-17',
                    'alamat' => 'Jl. Walang Barat No.52 RT.005/012 Kel. Tugu Utara Kec. Koja 14260',
                ],
                [
                    'nis' => '202523199',
                    'nisn' => '0071140926',
                    'nama' => 'MARCELLINO',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 42',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2007-09-25',
                    'alamat' => 'Jl. Rajawali Selatan I/44A RT.005/002 Kel. Gunung Sahari Utara Kec. Sawah Besar 10720',
                ],
                [
                    'nis' => '202523200',
                    'nisn' => '0091512920',
                    'nama' => 'MUHAMMAD FAUZAN KAMAL PUTRA',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 10',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-11-06',
                    'alamat' => 'Kebon Kosong 2 No.4 RT.014/401 Kel. Kebon Kosong Kec. Kemayoran 10630',
                ],
                [
                    'nis' => '202523201',
                    'nisn' => '0103742426',
                    'nama' => 'MUHAMMAD RAFA FADILAH',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMPM 12',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2010-05-05',
                    'alamat' => 'Kenanga RT.005/01 Kel. Kenanga Kec. Cipondoh 15146',
                ],
                [
                    'nis' => '202523202',
                    'nisn' => '0094085606',
                    'nama' => 'NAJWA FAJRINA AYATUL HUSNA',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 116',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-07-14',
                    'alamat' => 'Jl. Ancol Selatan No.15B RT.002/01 Kel. Sunter Agung Kec. Tanjung Priok 14350',
                ],
                [
                    'nis' => '202523203',
                    'nisn' => '0105016829',
                    'nama' => 'NAUVAL ARIEF HIBATULLOH',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 39',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2010-09-08',
                    'alamat' => 'Kp. Dubi Barat No.5 RT.002/09 Kel. Duri Pulo Kec. Gambir 11310',
                ],
                [
                    'nis' => '202523204',
                    'nisn' => '0095707225',
                    'nama' => 'NAYSHEILLA BILQIS HERYANTO',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 1',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-08-26',
                    'alamat' => 'Jl. Salemba Tengah Gg. IV No.134C RT.001/704 Kel. Senen Kec. Senen 10440',
                ],
                [
                    'nis' => '202523205',
                    'nisn' => '0097895043',
                    'nama' => 'NAZMU TORIQ',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 59',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-08-12',
                    'alamat' => 'Jl. Bendungan Jago RT.005/01 Kel. Serdang Kec. Kemayoran 10660',
                ],
                [
                    'nis' => '202523206',
                    'nisn' => '0093505154',
                    'nama' => 'QISYA AWFIYAH RAMADHANI',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 69',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-08-21',
                    'alamat' => 'Jl. Tawakal II A No.19 RT.005/09 Kel. Tomang Kec. Grogol Petamburan 11440',
                ],
                [
                    'nis' => '202523207',
                    'nisn' => '0097933788',
                    'nama' => 'RAMBUANA AHMAD ADNAN',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 139',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-11-22',
                    'alamat' => 'Kp. Rawa Badung RT.004/013 Kel. Jatinegara Kec. Cakung',
                ],
                [
                    'nis' => '202523208',
                    'nisn' => '0071167604',
                    'nama' => 'RAYHAN SAPUTRA',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP CEMPAKA',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2007-06-16',
                    'alamat' => 'Jl. Kampung Rawa Sawah RT.005/006 Kel. Kampung Rawa Kec. Johar Baru',
                ],
                [
                    'nis' => '202523209',
                    'nisn' => '0097763792',
                    'nama' => 'RAYVAN IRFANSYAH',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMPM 3',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-10-12',
                    'alamat' => 'Jl. I No.18 RT.007/09 Kel. Rawasari Kec. Cempaka Putih 10570',
                ],
                [
                    'nisn' => '202523210',
                    'nis' => '001591468',
                    'nama' => 'RIVAEL LIONEL MESSI BORYAN',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 116',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-04-01', // 04 Januari 2009
                    'alamat' => 'Jl. Pademangan III Gg. 10 No.20 RT.001/07 Kel. Pademangan Barat Kec. Pademangan 14410',
                ],
                [
                    'nisn' => '202523211',
                    'nis' => '003523271',
                    'nama' => 'SADDAM QADAFI NURAMA',
                    'gender' => 'LAKI-LAKI',
                    'asal_kelas' => 'SMP 65',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-10-26',
                    'alamat' => 'Jl. Warakas I No.118 RT.010/14 Kel. Warakas Kec. Tanjung Priok 14340',
                ],
                [
                    'nisn' => '202523212',
                    'nis' => '0098549147',
                    'nama' => 'SAFA OKTAFIANTI',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 284',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-10-24',
                    'alamat' => 'Jl. Biduri Bulan VIII RT.009/06 Kel. Sumur Batu Kec. Kemayoran 13950',
                ],
                [
                    'nisn' => '202523213',
                    'nis' => '0096879230',
                    'nama' => 'SALSA NABILA',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 40',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-05-28', // 28 Mei 2009
                    'alamat' => 'Gg. Panca Marga RT.007/01 Kel. Bendungan Hilir Kec. Tanah Abang 10210',
                ],
                [
                    'nisn' => '202523214',
                    'nis' => '0091226874',
                    'nama' => 'SITI SYEERA AZZAHRAH',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 255',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-07-02',
                    'alamat' => 'Jl. Nusa Indah VI Gg. I No.23 RT.002/03 Kel. Malaka Jaya Kec. Duren Sawit 13460',
                ],
                [
                    'nisn' => '202523215',
                    'nis' => '001595467',
                    'nama' => 'SYADIRA PUTRI AULIA',
                    'gender' => 'PEREMPUAN',
                    'asal_kelas' => 'SMP 42',
                    'tempat_lahir' => 'Jakarta',
                    'tanggal_lahir' => '2009-06-06',
                    'alamat' => 'Jl. Muara Bahari, Ancol Selatan RT.22 RW.01 No.69 Kel. Ancol Kec. Pademangan 14430'
                ],
        ];

        foreach ($siswas as $siswa) {
            DB::table('siswas')->insert([
                'nis' => $siswa['nis'],
                'nisn' => $siswa['nisn'],
                'name' => $siswa['nama'],
                'gender' => $siswa['gender'],
                'asal_sekolah' => $siswa['asal_kelas'],
                'slug'=>Str::random(8),
                'tempat_lahir'=>$siswa['tempat_lahir'],
                'tanggal_lahir'=>$siswa['tanggal_lahir'],
                'alamat'=>$siswa['alamat'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
